# Default values for sf-cluster-autoscaler.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  sfNodeManager:
    enabled: false
    priorityClassName: sf-critical-pod
  
  sfScheduler:
    enabled: false
    schedulerName: sf-scheduler
  
  snappyflowProjectLabel: snappyflow/projectname
  snappyflowAppLabel: snappyflow/appname

  snappyflowProjectName: "snappyflow-app"
  snappyflowAppName: "sf-cluster-autoscaler"

replicaCount: 1
namespace: default
image:
  repository: k8s.gcr.io/autoscaling/cluster-autoscaler
  pullPolicy: IfNotPresent
  tag: v1.20.0

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

overProvisionerResources:
  requests:
    cpu: 1000m
    memory: 5Gi

autoscaler:
  # Specifies whether a autoscaler should be created. Set true in case of AWS
  enabled: true
  nodeUnneededTime: 3600s
  serviceAccountName: ""
  resources:
    requests:
      cpu: 500m
      memory: 500Mi

overProvisioning:
  enabled: false

# Needed in case of eks
eks:
  clusterName: ""
  rolearn: ""
