apiVersion: v1
appVersion: "1.0"
description: A Helm chart to deploy expressCart nodejs application
name: expresscart
icon: https://raw.githubusercontent.com/mrvautin/expressCart/master/public/images/logo.png
sources:
- https://github.com/mrvautin/expressCart
version: 0.2.3
