apiVersion: v2
name: keycloak
description: A Helm chart for Kubernetes
type: application
version: 1.6.5
appVersion: 1.0.0

dependencies:
- name: postgresql
  version: 0.1.13
  repository: https://snappyflow.github.io/helm-charts/
  condition: postgresql.enabled
