{{- if .Values.external.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "cp-kafka-rest.fullname" . }}-external
  {{- if .Values.external.annotations }}
  annotations:
  {{- range $key, $value := .Values.external.annotations }}
    {{ $key }}: "{{ $value }}"
  {{- end }}
  {{- end }}
  labels:
    app: {{ template "cp-kafka-rest.name" . }}
    chart: {{ template "cp-kafka-rest.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    app: {{ template "cp-kafka-rest.name" . }}
    release: {{ .Release.Name }}
  type: {{ .Values.external.type }}
  externalTrafficPolicy: {{ .Values.external.externalTrafficPolicy }}
  {{ if (eq .Values.external.type "LoadBalancer") }}
  loadBalancerSourceRanges:
  {{ range $cidr := .Values.external.loadBalancerSourceRanges }}
    - {{ $cidr }}
  {{ end }}
  {{ end }}
  ports:
    {{ if (eq .Values.external.type "NodePort") }}
    - name: rest-proxy
      port: {{ .Values.servicePort }}
      nodePort: {{ .Values.external.nodePort }}
    {{ if .Values.https.enabled }}
    - name: rest-proxy-https
      port: {{ .Values.httpsServicePort }}
      nodePort: {{ .Values.external.httpsNodePort }}
    {{ end }}
    {{- else -}}
    - name: rest-proxy
      port: {{ .Values.servicePort }}
    {{- if .Values.https.enabled }}
    - name: rest-proxy-https
      port: {{ .Values.httpsServicePort }}
    {{- end }}
    {{- end -}}
{{- end -}}
