{{- if .Values.https.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-rest-tls-secret
  namespace: {{ .Release.Namespace }}
  labels:
    release: {{ .Release.Name }}
data:
  {{ .Values.https.truststoreFile }}: |-
{{- $path := printf "certs/%s" .Values.https.truststoreFile }}
{{ .Files.Get $path | b64enc | indent 4 }}
  {{ .Values.https.keystoreFile }}: |-
{{- $path := printf "certs/%s" .Values.https.keystoreFile }}
{{ .Files.Get $path | b64enc | indent 4 }}
stringData:
  keystorePassword: {{ .Values.https.keystorePassword }}
  keyPassword: {{ .Values.https.keyPassword }}
  truststorePassword: {{ .Values.https.truststorePassword }}
{{- end }}
