apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "sf-node-manager.fullname" . }}
  labels:
    app: {{ include "sf-node-manager.name" . }}
    release: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  selector:
    matchLabels:
      app: {{ include "sf-node-manager.name" . }}
      role: sf-node-manager
  template:
    metadata:
      labels:
        app: {{ include "sf-node-manager.name" . }}
        release: {{ .Release.Name }}
        {{ .Values.global.snappyflowProjectLabel}}: {{ .Values.global.snappyflowProjectName }}
        {{ .Values.global.snappyflowAppLabel }}: {{ .Values.global.snappyflowAppName }}
        role: sf-node-manager
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      {{- if .Values.global.sfNodeManager.enabled }}
      priorityClassName: {{ .Values.global.sfNodeManager.priorityClassName }}
      {{- end }}
      {{- if .Values.global.sfScheduler.enabled }}
      schedulerName: {{ .Values.global.sfScheduler.schedulerName }}
      {{- end }}
      containers:
        - name: nodemanager
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          command: ["/bin/bash", "-c"]
          args: ["./manager;"]
          env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName 
