apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "postgresql.fullname" . }}-sfagent
  labels:
    {{- include "postgresql.labels" . | nindent 4 }}

data:
  config.yaml: |-
    key: "{{ .Values.global.key }}"
    metrics:
        plugins:
        - name: postgres
          enabled: true
          interval: 30
          config:
            port: 5432
            host: 127.0.0.1
            user: {{ .Values.rootUser }}
            password: {{ .Values.rootPassword }}
            documentsTypes:
              - databaseDetails
              - indexDetails
              - queryDetails
              - serverDetails
              - tableDetails
    {{- if .Values.global.loggingCollector.enabled }}
    logging:
        plugins:
        - name: postgres-general
          enabled: true
          config:
            log_level:
              - error
              - warning
              - info
              - log
            log_path: /var/log/postgres/*.log
        - name: postgres-slowquery
          enabled: true
          config:
            log_path: /var/log/postgres/*.log
    {{- end }}
