apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "postgresql.fullname" . }}
  labels:
    {{- include "postgresql.labels" . | nindent 4 }}
    snappyflow/component: postgresql
    {{ default "snappyflow/appname" .Values.global.sfappname_key }}: {{ default .Release.Name .Values.global.sfappname }}
    {{ default "snappyflow/projectname" .Values.global.sfprojectname_key }}: {{ default .Release.Name .Values.global.sfprojectname }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "postgresql.selectorLabels" . | nindent 6 }}
  serviceName: {{ .Chart.Name }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "postgresql.selectorLabels" . | nindent 8 }}
        snappyflow/component: postgresql
        {{ default "snappyflow/appname" .Values.global.sfappname_key }}: {{ default .Release.Name .Values.global.sfappname }}
        {{ default "snappyflow/projectname" .Values.global.sfprojectname_key }}: {{ default .Release.Name .Values.global.sfprojectname }}
    spec:
      {{- if .Values.global.sfScheduler.enabled }}
      schedulerName: {{ .Values.global.sfScheduler.schedulerName }}
      {{- end }}
      {{- if .Values.global.sfNodeManager.enabled }}
      priorityClassName: {{ .Values.global.sfNodeManager.priorityClassName }}
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "postgresql.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        {{- if .Values.global.key }}
        - name: postgresql-agent
          image: snappyflowml/sfagent:latest
          imagePullPolicy: Always
          command:
          - /app/sfagent
          - -config-file
          - /opt/sfagent/config.yaml
          - -enable-console-log
          env:
          - name: APP_NAME
            value: {{ .Values.global.sfappname }}
          - name: PROJECT_NAME
            value: {{ .Values.global.sfprojectname }}
          volumeMounts:
          - name: sfagent
            mountPath: /opt/sfagent/config.yaml
            subPath: config.yaml
          {{- if .Values.global.loggingCollector.enabled }}
          - name: varlog
            mountPath: /var/log/postgres
          {{- end }}
        {{- end }}
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.global.loggingCollector.enabled }}
          args: ["-c", "log_statement=all", "-c", "log_min_messages=warning", "-c", "log_min_duration_statement=200", "-c", "log_directory=/var/log/postgres", "-c", "log_line_prefix=< %m > ", "-c", "log_filename=postgresql-%Y-%m-%d_%H%M%S.log", "-c", "log_truncate_on_rotation=off", "-c", "log_rotation_age=1d", "-c", "logging_collector=on"]
          {{- end }}
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "postgresql.fullname" . }}
                  key: rootPassword
            - name: PG_MULTI_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "postgresql.fullname" . }}
                  key: multidbUserPassord
            - name: POSTGRES_USER
              value: {{ .Values.rootUser }}
            - name: PG_MULTI_DB_USER
              value: {{ .Values.multidbUser }}
            - name: PG_MULTI_DB
              value: {{ .Values.multidb }}
            - name: PGDATA
              value: "/data/pgdata"
          ports:
            - name: tcp
              containerPort: 5432
              protocol: TCP
          readinessProbe:
            exec:
              command:
                - sh 
                - -c 
                - "pg_isready -U ${POSTGRES_USER}"
            initialDelaySeconds: 30
            timeoutSeconds: 5
          livenessProbe:
            exec:
              command:
                - sh 
                - -c 
                - "pg_isready -U ${POSTGRES_USER}"
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 5
          volumeMounts:
          - name: data
            mountPath: /data
            subPath: pgdata
          {{- if .Values.initconfig }}
          - name: initconfig
            mountPath: /docker-entrypoint-initdb.d
          {{- end }}
          {{- if .Values.global.loggingCollector.enabled }}
          - name: varlog
            mountPath: /var/log/postgres
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      - name: data
      {{- if .Values.persistence.enabled }}
        persistentVolumeClaim:
          claimName: {{ include "postgresql.fullname" . }}
      {{- else }}
        emptyDir: {}
      {{- end }}
      {{- if .Values.global.loggingCollector.enabled }}
      - name: varlog
        emptyDir: {} 
      {{- end }}
      {{- if .Values.initconfig }}
      - name: initconfig
        configMap:
          name: {{ include "postgresql.fullname" . }}-init
      {{- end }}
      - name: sfagent
        configMap:
          name: {{ include "postgresql.fullname" . }}-sfagent
      
