apiVersion: v2
name: sf-saas-metrics
description: A Helm chart for Kubernetes
type: application
version: 1.0.1
appVersion: "1.16.0"
dependencies:
- name: prometheus
  repository: https://prometheus-community.github.io/helm-charts
  version: 19.3.1
- name: prometheus-adapter
  repository: https://prometheus-community.github.io/helm-charts
  version: 4.0.0
