apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "charging.fullname" . }}-config
  labels:
    {{- include "charging.labels" . | nindent 4 }}
    app: charging
    role: server
data:
    {{- if .Values.postgresql.enabled }}
    DB_HOST: {{ .Release.Name }}-postgresql
    DB_PORT: "5432"
    DB_NAME: "apmbilling"
    DB_USER: {{ .Values.postgresql.multidbUser }}
    {{- else }}
    DB_HOST: {{ .Values.postgresql.external.dbHost }}
    DB_PORT: {{ .Values.postgresql.external.dbPort | default "5432"  | quote }}
    DB_NAME: "apmbilling"
    DB_USER: {{ .Values.postgresql.external.dbUser }}
    DB_PASSWORD: {{ .Values.postgresql.external.dbPassword }}
    {{- end }}
    REDIS_HOST: {{ .Release.Name  }}-redis
    REDIS_PORT: "6379"
    HOURLY_DATA_RETAIN_DAYS: {{ .Values.hourly_data_retain_days | quote }}

    KEYCLOAK_SERVER: {{ .Values.keycloak_server | quote }}
    KEYCLOAK_USER: {{ .Values.keycloak_user | quote }}
    KEYCLOAK_PASSWORD: {{ .Values.keycloak_password | quote }}
    KEYCLOAK_REALM: {{ .Values.keycloak_realm | quote }}
    KEYCLOAK_CLIENTID: {{ .Values.keycloak_clientid | quote }}
    KEYCLOAK_CLIENTKEY: {{ .Values.keycloak_clientkey | quote }}
    KEYCLOAK_PUBLICKEY: {{ .Values.keycloak_publickey | quote }}
    
    
    EMAIL_HOST: {{ .Values.email_host | quote }}
    EMAIL_HOST_PASSWORD: {{ .Values.email_host_password | quote }}
    EMAIL_HOST_USER: {{ .Values.email_host_user | quote }}
    EMAIL_PORT: {{ .Values.email_port | quote }}
    EMAIL_BACKEND: {{ .Values.email_backend | quote }}
    EMAIL_TIMEOUT: "10"
    EMAIL_USE_TLS: "true"
    SUPPORT_EMAIL: {{ .Values.support_email | quote }}

    GATEWAYID: {{ .Values.gatewayid | quote }}
    CHARGEBEE_NAME: {{ .Values.chargebee_name | quote }}
    CHARGEBEE_KEY: {{ .Values.chargebee_key | quote }}
    STRIPE_KEY: {{ .Values.stripe_key | quote }}
    SALES_TEAM_MAIL: {{ .Values.sales_team_mail | quote }}

    AWS_ACCESS_KEY : {{ .Values.aws_access_key | quote }}
    AWS_SECRET_KEY : {{ .Values.aws_secret_key | quote }}
    S3_BUCKET_NAME : {{ .Values.s3_bucket_name | quote }}

    {{- if .Values.ingest_usage_system.enabled }}
    USAGE_SYSTEM_HOST: "{{ .Values.ingest_usage_system.host }}"
    USAGE_SYSTEM_PORT: "{{ .Values.ingest_usage_system.port }}"
    {{- end }}
