# Default values for charging.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
enableDebug: false

replicaCount: 1

global:
  sfScheduler:
    enabled: false
    schedulerName: sf-scheduler

component: snappyflow-apm

image:
  repository: snappyflowml/charging
  pullPolicy: Always
  tag: release

# controls period for which hourly data is retained
# setting value to 0 disables clean up
hourly_data_retain_days: 0

# change these please provide base64 encode certificate and its keys
# use command base64 -w 0 <filename>
tls_key:
tls_cert:

#Keycloak settings
keycloak_server: ""
keycloak_user: ""
keycloak_password: ""
keycloak_realm: ""
keycloak_clientid: ""
keycloak_clientkey: ""
keycloak_publickey: ""

#Email settings
email_host: ""
email_host_password: ""
email_host_user: ""
email_port: 587
email_backend: ""
email_timeout: 10
email_use_tls: true
support_email: "stage-snappyflow-support@snappyflow.io"

# aws  settings
aws_access_key: ""
aws_secret_key: ""
s3_bucket_name: ""

#Chargebee settings
gatewayid: ""
chargebee_name: ""
chargebee_key: ""
stripe_key: ""
sales_team_mail: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: false
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 8000

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths: []
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
  limits:
    cpu: 500m
    memory: 250Mi
  requests:
    cpu: 250m
    memory: 128Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 70
  # targetMemoryUtilizationPercentage: 70

nodeSelector: {}

tolerations: []

affinity: {}

celery:
  env:
    C_FORCE_ROOT: true
    CELERY_OPTS: "-O fair --max-tasks-per-child 20 -P gevent"
  beat:
    command: "celery -A charging beat -l $LOG_LEVEL"
  default:
    replicaCount: 1
    command: "celery -A charging worker -n charging@%n -l $LOG_LEVEL -c10 $CELERY_OPTS"
  resources:
    limits:
      cpu: 1000m
      memory: 500Mi
    requests:
      cpu: 250m
      memory: 128Mi

redis:
  image:
    repository: redis
    pullPolicy: IfNotPresent
    tag: "5.0"
  persistence:
    enabled: true
    storageClass: ""
    size: 4Gi
  config:
    redis.conf: |-
      appendonly yes
      maxmemory 100mb
      maxmemory-policy allkeys-lru
  resources:
    limits:
      cpu: 1000m
      memory: 500Mi
    requests:
      cpu: 100m
      memory: 128Mi
  podAnnotations:
    prometheus.io/scrape: "false"

postgresql:
  # enabled true deploys postgresql as statefull set on the same cluster
  enabled: true

  # if enabled false, chart will connect to external database
  # create base with names apmbilling
  # create a user and grant access to database apmbilling
  # provide external section is required if postgresql.enabled is false

  # external:
  #   dbHost: "test-db-postgresql"
  #   dbPort: ""
  #   dbUser: "test"
  #   dbPassword: "test123"

  image:
    repository: postgres
    pullPolicy: IfNotPresent
    tag: "9.6"
  persistence:
    enabled: true
    storageClass: ""
    size: 8Gi
  # when local postgresql is enabled below values are used to configure database
  rootPassword: postgres
  rootUser: postgres
  multidb: apmbilling
  multidbUser: snappyflow
  multidbUserPassord: maplelabs

ingest_usage_system:
  enabled: false
  host: ""
  port: 443
  use_tls: False

global:
  sfappname: apm-billing
  sfprojectname: apmdemo-sf-io
  sfappname_key: snappyflow/appname
  sfprojectname_key: snappyflow/projectname
  key: ""
